# Generated by Django 2.2.4 on 2019-08-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_auto_20190821_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieferung',
            name='produkte',
        ),
        migrations.AddField(
            model_name='lieferung',
            name='produkte',
            field=models.ManyToManyField(to='ordering.Produkt'),
        ),
    ]
