# Generated by Django 2.2.4 on 2019-08-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_auto_20190821_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieferung',
            name='ort',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lieferung',
            name='strasse',
            field=models.CharField(max_length=60),
        ),
    ]
