# Generated by Django 2.2.4 on 2019-08-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_auto_20190821_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lieferung',
            options={'verbose_name': 'Lieferung', 'verbose_name_plural': 'Lieferungen'},
        ),
    ]
