# Generated by Django 2.2.4 on 2019-08-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_auto_20190828_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieferung',
            name='nachname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lieferung',
            name='vorname',
            field=models.CharField(default='Peter', max_length=50),
            preserve_default=False,
        ),
    ]
