# Generated by Django 2.2.4 on 2019-08-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_auto_20190828_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieferung',
            name='hausnummer',
            field=models.CharField(default=7, max_length=30),
            preserve_default=False,
        ),
    ]
