# Generated by Django 2.2.4 on 2019-08-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0007_lieferung_hausnummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieferung',
            name='ausgeliefert',
            field=models.BooleanField(default=False),
        ),
    ]
