# Generated by Django 2.2.4 on 2019-08-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0008_lieferung_ausgeliefert'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='zutaten',
            field=models.ManyToManyField(to='ordering.Zutaten'),
        ),
    ]
